export default {
  REGISTER_MODAL: 'REGISTER_MODAL',
  SIGN_IN_MODAL: 'SIGN_IN_MODAL',
  DELETE_ITEM_MODAL: 'DELETE_ITEM_MODAL',
  ADD_ITEM_MODAL: 'ADD_ITEM_MODAL',
  EDIT_ITEM_MODAL: 'EDIT_ITEM_MODAL',
};
