export default {
  REGISTER_MODAL: 'REGISTER_MODAL',
  SIGNIN_MODAL: 'SIGNIN_MODAL',
  DELETE_ITEM_MODAL: 'DELETE_ITEM_MODAL',
  ADD_ITEM_MODAL: 'ADD_ITEM_MODAL',
  EDIT_ITEM_MODAL: 'EDIT_ITEM_MODAL',
};
